#+title: Collected Quotations
#+options: author:nil date:nil toc:nil

#+begin_quote
“The mass of men lead lives of quiet desperation."

--- Henry David Thoreau, from /Civil Disobedience and Other Essays/.
#+end_quote

#+begin_quote
“Today I will do what other's won't, so tomorrow I will do what others can't.”

--- Jerry Rice
#+end_quote

#+begin_quote
"Considering how  many  fools  can  calculate,  it  is  surprising  that  it
should be thought either a difficult or a tedious task for any other fool to
learn how to master the same tricks. Some calculus-tricks are quite easy.  Some
are enormously difficult. The fools who write the textbooks of advanced
mathematics --- and they are mostly clever fools --- seldom take the trouble to
show you how easy the  easy  calculations  are.

On the contrary, they seem to desire to impress you with their tremendous
cleverness by going about it in the most difficult way. Being myself a
remarkably stupid fellow, I have had to unteach myself the difficulties,
and now beg to present to my fellow fools the parts that are not hard.
Master these thoroughly, and the rest will follow.

What one fool can do, another can."

--- Slivanus P Thompson, from the preface of /Calculus Made Easy/.
#+end_quote

#+begin_quote
"One must imagine Sisyphus happy."

--- Albert Camus
#+end_quote

#+begin_quote
"Then I saw that there was a way to hell, even from the gates of heaven."

--- John Bunyan, from /The Pilgrim's Progress/.
#+end_quote

#+begin_quote
“You never conquer a mountain. You stand on the summit a few brief minutes and then the wind blows away your footprints.”

--- Arlene Blum
#+end_quote

#+begin_quote
"It takes a lifetime to master the shakuhachi. The earlier you start, the longer it takes."

--- Anonymous
#+end_quote

#+begin_quote
"The mind is not a vessel to be filled, but a fire to be kindled."

--- Plutarch
#+end_quote

#+begin_quote :work:
"Work spares us from three evils: boredom, vice, and need."

--- Voltaire
#+end_quote

#+begin_quote
"Grief, I’ve learned, is really just love. It’s all the love you want to give,
but cannot. All that unspent love gathers up in the corners of your eyes, the
lump in your throat, and in that hollow part of your chest. Grief is just love
with no place to go."

--- Jamie Anderson
#+end_quote

#+begin_quote
"The separation of talent and skill is one of the greatest misunderstood
concepts for people who are trying to excel, who have dreams, who want to do
things. Talent you have naturally. Skill is only developed by hours and hours
and hours of beating on your craft."

--- Will Smith
#+end_quote

#+begin_quote
"my body renews itself in waves of ocean and blood"

--- rupi kaur
#+end_quote

#+begin_quote
"I saw my life branching out before me like the green fig tree in the story.
From the tip of every branch, like a fat purple fig, a wonderful future beckoned
and winked. One fig was a husband and a happy home and children, and another fig
was a famous poet and another fig was a brilliant professor, and another fig was
Ee Gee, the amazing editor, and another fig was Europe and Africa and South
America, and another fig was Constantin and Socrates and Attila and a pack of
other lovers with queer names and offbeat professions, and another fig was an
Olympic lady crew champion, and beyond and above these figs were many more figs
I couldn't quite make out. I saw myself sitting in the crotch of this fig tree,
starving to death, just because I couldn't make up my mind which of the figs I
would choose. I wanted each and every one of them, but choosing one meant losing
all the rest, and, as I sat there, unable to decide, the figs began to wrinkle
and go black, and, one by one, they plopped to the ground at my feet."

--- Sylvia Plath
#+end_quote

#+begin_quote
“The most important step a man can take. It's not the first one, is it?
It's the next one. Always the next step, Dalinar.”

--- Brandon Sanderson, Oathbringer
#+end_quote

#+begin_quote
"The axe forgets; the tree remembers."

--- African proverb
#+end_quote

#+begin_quote
"Talk is cheap."
#+end_quote

#+begin_quote
"Data, data, data! I cannot make bricks without clay."

--- Sherlock Holmes
#+end_quote

#+begin_quote
"Work expands so as to fill the time available for its completion."

--- Parkinson's Law
#+end_quote

#+begin_quote
"To improve  is to change; to be perfect  is to change often"

--- Winston  Churchill
#+end_quote

#+begin_quote
"I believe the common denominator of the universe is not harmony, but chaos,
hostility, and murder."

--- Werner Herzog
#+end_quote

#+begin_quote
"You must take your opponent into a deep dark forest where 2+2=5, and the path
leading out is only wide enough for one."

--- Mikhail Tal
#+end_quote

#+begin_quote
"There is a pleasure in the pathless woods,
There is rapture in the lonely shore,
There is a society where none intrude,
I love not man less, but nature more."

--- George Gordon, Lord Byron
#+end_quote
