#+title: Wheel of Time Notes
#+options: toc:nil

*WARNING!* These notes contain spoilers and working theories for the Wheel of Time series by Robert Jordan.

Reading progress:
1. [-] /The Eye of the World/
2. [ ] /The Great Hunt/
3. [ ] /The Dragon Reborn/

#+toc: headlines 2

* Characters
** Rand al'Thor

Son of [[*Tam al'Thor][Tam al'Thor]] and Kari (sp?)
** Perrin Aybara
** Matrim Cauthon
** Thom Merrilin
** Moiraine
** Lan
** Padan Fain
** Elyas
** Tam al'Thor

Father of [[*Rand al'Thor][Rand al'Thor]]

Backstory:
Possibly master swordsman

** Egwene
** Nynaeve
** Min
** Ba'alzamon
* Significant Figures
For figures that are mentioned or in other ways do not directly interact with other characters
** The Dark One
** Shai'tan
** False Dragons
+ Logain
** Artur Paendrag Hawking

* Dreams and Visions
** Rand's First Dream
Pursued in a wasteland towards a black mountain. Felt called towards it. Refused
and (possibly traveled) to Tar Valon. Upon entering the city he was encouraged
to go towards the tower. When he does he is showered with flowers until he
enters and sees the Fade.
** The First Dream of Ba'alzamon
Rand, Mat, and Perrin had the same dream with differing details.

Running around a castle thirsty with the sound of dripping water.

Upon entering a room, Ba'alzamon is standing in front of a fireplace where the
oval stones look like faces twisted in pain and horror.  Outside the window a
storm of red and grey clouds rages.  He offers a drink which Rand refuses. He
then threatens Rand and breaks the back of the goblet turned rat.

On waking, Rand discovers many many rats in the inn with her back broken.
** Min's Visions of the Pattern
_Rand_
_Mat_
_Lan_
Seven broken towers
An infant in a crib holding a sword
_Perrin_
Wolves
** Rand's Pursuit in the Maze

** Perrins Wolf dreams
Perrin is
* Symbols
** Symbol of the Aes Sedai
Resembles yin yang, but also possibly two interlocked Dragon Teeth
** The Dragon Tooth
** The Heron

Sign of a master swordsman.

Occurances:
Tam al'Thors scabbard
Recognised by Trollocs and Warder Lan

* Monsters and Creatures
** Trollocs
** Drakahr
** Halfmen Fades
** Darkfriends
** Forsaken
* Factions and Groups
** Aes Sedai

** Warders

** Children of the Light
From/headquarters: Amador?
Known members:
+ Child Byar
+ Lord Captain Geofram Bornhald (Anointed of the Light [title])
  - Has a son Dain

Ranks/Titles:
+ Questioners
+ Lord Captain
+ Anointed of the Light

Tenets:
+ "No man is so lost that he cannot be brought to the Light."

** Forsaken
** Women's Circle of Emond's Field
** Village Council of Emond's Field
* Histories
** Age of Legends
** Time of Madness
** War of Hundred Years
* Myths
** Breaking of the World

** Stone of Tear

** Hunt for the Horn
* Locations
** Tar Valon
** Stedding of Artur Hawkwing
** Two Rivers
** Emond's Field
** Taren Ferry
** Whitebridge
** Caemlyn
** Baerlon
** Shadar Logoth
* Magic and Metaphysics
** Time and Ages
** The Pattern
** True Source
** One Power
Saidan saitan male/female representations
** Stedding
** Wolfkin
Known practitioners: Elyas, Perrin (acolyte/unrealised)
Abilities: mental link/telepathy with wolves.
* Working Theories
** The Female Half of the One Power is Tainted
    _Supporting evidence:_
    1. In /The Eye of the World/ Nynaeve notes that she can feel a sickly oily energy flowing around them.
        If the male half of the One Power is inaccessible to her, then she must be feeling the female half of the power, which feels tainted.
    2. Use of the One Power by women has a negative effect on them. Touching the One Power without guidance or training is considered dangerous.
